// 友链检测 CLI 需要使用显式导入和相对路径
import type { FeedGroup } from '../app/types/feed'

export default [
	// #region Clarity
	{
		name: '膜拜大佬',
		desc: '技术实力强、影响力大的博主，值得学习膜拜',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '安知鱼',
				sitenick: '',
				title: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				linkpage: 'https://blog.anheyu.com/link/',
				feed: 'https://blog.anheyu.com/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390c93e2c4f.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390c93e2c4f.png',
				archs: ['Golang', 'EdgeOne'],
				date: '2024-12-09',
				comment: '聚焦前端技术与Anheyu-App相关，分享CSS新方案、React漏洞、CSRF攻击等技术解析，及应用安装迁移教程，也含Mac使用体验、武汉旅游日志与年度总结，技术实用且兼顾生活气息。',
			},
			{
				author: '张洪Heo',
				sitenick: '',
				title: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				linkpage: 'https://blog.zhheo.com/link/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e343ad1a7bf.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e343ad1a7bf.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '聚焦设计与科技生活。内容含Mac/iOS软件推荐、iPhone17上手体验、Final Cut Pro剪辑技巧、智能家居接入等实用经验，也有闲聊杂谈与年度博主推荐，兼具数码干货与生活气息。',
			},
			{
				author: '纸鹿',
				sitenick: '摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				linkpage: 'https://blog.zhilu.site/link',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390d1a2ed5e.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390d1a2ed5e.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-12-09',
				comment: '聚焦前端开发、系统配置与数码体验，分享VitePress优化、深浅色模式等技术指南，及ArchLinux安装、数码“捡垃圾”心得，也有生活杂谈与避坑经验，实用又有温度。',
			},
			{
				author: '周润发',
				sitenick: '',
				title: '周润发',
				desc: '收录开源，好用的互联网项目',
				link: 'https://blog.zrf.me/',
				linkpage: 'https://blog.zrf.me/links/',
				feed: 'https://blog.zrf.me/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3447e7e8a1.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3447e7e8a1.webp',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '周润发博客是技术极客与生活观察者的跨界空间，聚焦开源工具与互联网实用项目分享。近期深度测评Cloudflare边缘证书部署、Vercel加速优化等硬核技术，揭秘临时邮箱搭建、订阅链接聚合等开发者刚需，并记录换电池翻车、域名抢注等趣味日常。内容横跨网络安全、系统调优、AI应用等领域，风格务实接地气，通过代码片段与实操指南降低技术门槛，同时以幽默笔触消解工具理性，是极客圈的宝藏工具库与治愈系精神角落。',
			},

		],
	},
	{
		name: '相谈甚多',
		desc: '经常互动、关系密切的博主',
		entries: [
			{
				author: 'klcdm',
				sitenick: '朽丘秋雨',
				title: '朽丘秋雨',
				desc: '一定会和喜欢的人在夏日夜晚牵手慢步',
				link: 'https://koxiuqiu.cn/',
				linkpage: 'https://koxiuqiu.cn/link/',
				feed: 'https://koxiuqiu.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3447e8fe02.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3447e8fe02.webp',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '近期调整个人状态后将恢复季更。内容以生活日志、月度/年度总结为主，谈及亲情、代际观念等感悟，也有情感杂语与暂别絮语，满含个人真实思绪与生活烟火气。',
			},
			{
				author: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮',
				sitenick: '',
				title: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮',
				desc: '人生漫长，不妨多解锁些鲜活体验',
				link: 'https://blog.fis.ink/',
				linkpage: 'https://blog.fis.ink/link',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390da15f86e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390da15f86e.webp',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '2025年5月曾遭遇服务器攻击并处理CDN相关问题。内容涵盖运维部署（1panel搭建备案系统、哪吒监控美化）、设备体验、问题排查，也有音乐播放器分享、爱国图片合集等，实用与情怀兼具。',
			},
			{
				author: 'Liushen',
				sitenick: '清羽飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				linkpage: 'https://blog.liushen.fun/link/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390d7ce4a02.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390d7ce4a02.png',
				archs: ['Astro', 'EdgeOne'],
				date: '2025-01-01',
				comment: '近期在成都活动、学 C++，曾感冒。文章多涉 Hexo/Butterfly 主题魔改、Anheyu-App 部署、TinyAuth 认证等筑站运维内容，也有旅游、观影类闲情杂记。',
			},
			{
				author: 'Xuan\'s blog',
				sitenick: '',
				title: 'Xuan\'s blog',
				desc: '分享技术教程和学习笔记',
				link: 'https://blog.ybyq.wang/',
				linkpage: 'https://blog.ybyq.wang/friends.html',
				feed: 'https://blog.ybyq.wang/feed/',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390dd5af202.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390dd5af202.webp',
				archs: ['Typecho', '国内 CDN'],
				date: '2024-12-09',
				comment: '站长获项目劳务费，记录晚霞、中秋游记等生活点滴。内容涵盖Umami升级、Typecho博客运维（主题美化、插件监控等）教程，及GPT聊天应用、健身房管理系统开发实践，兼具技术干货与生活随笔。',
			},
		],
	},
	// #endregion
	// #region 网上邻居
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梦爱吃鱼',
				sitenick: '',
				title: '梦爱吃鱼',
				desc: '但愿日子清静抬头遇见的满是柔情',
				link: 'https://blog.bsgun.cn/',
				linkpage: 'https://blog.bsgun.cn/link',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e34feded13d.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e34feded13d.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '聚焦Hexo博客主题魔改，分享首页样式优化、侧边栏组件添加（评论、倒计时等）、宠物挂件等教程，也含开源项目盘点与工具部署方案，专注博客美化与功能拓展。',
			},
			{
				author: 'FrWalker',
				sitenick: '',
				title: 'FrWalker',
				desc: '听风雨，问星辰，随心归✨',
				link: 'https://blog.frwalker.top/',
				linkpage: 'https://blog.frwalker.top/link/',
				feed: 'https://blog.frwalker.top/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3556593102.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3556593102.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '站长近期专注创作，博客以Linux技术与开源项目为核心。有Linux系统安装、配置教程，也分享开源项目实践经验。致力于为Linux爱好者与开发者提供专业知识，助力在开源世界探索前行。 ',
			},
			{
				author: '葱苓sama',
				sitenick: '葱苓小筑',
				title: '葱苓小筑',
				desc: '风带来了故事的种子，时间使其发芽。',
				link: 'https://blog.ciraos.top/',
				linkpage: 'https://blog.ciraos.top/link',
				feed: 'https://blog.ciraos.top/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e355a48e79e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e355a48e79e.webp',
				archs: ['Golang', '国内 CDN'],
				date: '2024-12-09',
				comment: '该博客站长当下专注创作，文章多为软件资源分享及使用教程，像各类实用工具、办公软件等。也涵盖电脑系统优化技巧，聚焦数码软件领域，为用户提供便捷高效的使用指南与资源。 ',
			},
			{
				author: 'Mo的记事簿',
				sitenick: '',
				title: 'Mo的记事簿',
				desc: '万年鸽王，哈哈OvO',
				link: 'https://blog.xiowo.net/',
				linkpage: 'https://blog.xiowo.net/link/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390f13a6a9e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390f13a6a9e.webp',
				archs: ['Hexo', 'Netlify'],
				date: '2024-12-09',
				comment: '聚焦Hexo博客搭建与美化，分享安知鱼主题配置、Twikoo评论优化等教程，也涵盖Emby代理、Android网络修复、GitHub加速等工具使用技巧，兼具技术笔记与实用指南，干货满满。',
			},
			{
				author: '壹人小站',
				sitenick: '',
				title: '壹人小站',
				desc: 'Trust the process.',
				link: 'https://www.xscnet.cn/',
				linkpage: 'https://www.xscnet.cn/links/',
				feed: 'https://www.xscnet.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a390fd3517d2.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a390fd3517d2.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '站长为高三学生，将在2026年6月高考后回归。内容含站点CDN优化、数码推荐、音乐分享、日常小结，还开发过游戏存档同步工具，兼具建站技术、生活点滴与兴趣分享。',
			},
			{
				author: '夜轻Blog',
				sitenick: '',
				title: '夜轻Blog',
				desc: '一个人',
				link: 'https://blog.yeqing.net/',
				linkpage: 'https://blog.yeqing.net/friend.html/',
				feed: 'https://blog.yeqing.net/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a39101d73f24.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a39101d73f24.webp',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '站长提及疲惫想停下，启用新域名qzq.im。内容聚焦免费互联网服务、VPS与CDN（零九、橘喵云等）使用体验，也含随机图片API文档制作，主打网络服务测评与实用资源分享。',
			},
			{
				author: '❖星港◎Star☆',
				sitenick: '',
				title: '❖星港◎Star☆',
				desc: '以博客记录生活与热爱！',
				link: 'https://blog.starsharbor.com/',
				linkpage: 'https://blog.starsharbor.com/links/',
				feed: 'https://blog.starsharbor.com/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3910e51a153.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3910e51a153.webp',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '记录建站多周年历程与上海旅行纪念。内容涵盖HarmonyOS NEXT系统体验、solitude主题配置（字体/友链/数据统计）等技术分享，也有原神版本梳理、饮品测评、华为手表使用记录，兼具技术实践与生活随笔，风格多元。',
			},
			{
				author: '百里博客',
				sitenick: '',
				title: '百里博客',
				desc: '一个高中生的博客',
				link: 'https://blog.my0811.cn/',
				linkpage: 'https://blog.my0811.cn/friends/',
				feed: 'https://blog.my0811.cn/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a391142a762f.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a391142a762f.png',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '专注技术实践与实用教程。内容涵盖Android逆向（喵窝计账破解）、Qwen3-Coder大模型安装、Fuwari博客追番列表接入，及Python步数自动化脚本开发，聚焦逆向工程、AI编程与博客定制，干货实用且落地性强。',
			},
			{
				author: 'AirTouch',
				sitenick: '',
				title: 'AirTouch',
				desc: 'Stay Hungry, Stay Foolish',
				link: 'https://www.xsl.im/',
				linkpage: 'https://www.xsl.im/friends',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3797e7c630.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3797e7c630.webp',
				archs: ['Nuxt', '服务器'],
				date: '2024-12-09',
				comment: '近期更新Stellar主题。内容聚焦技术折腾与项目分享，含Artalk评论区配置、Hexo AI摘要等博客优化教程，Librechat AI部署、临时邮箱搭建等项目推荐，还有VPS测评与系统问题解决方案，技术实用且覆盖多元场景。',
			},
			{
				author: '叶泯希',
				sitenick: '',
				title: '叶泯希',
				desc: '意义是自己赐予的',
				link: 'https://blog.418121.xyz/',
				linkpage: 'https://blog.418121.xyz/links/',
				feed: 'https://blog.418121.xyz/rss2.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/19/69e42ae892c5a.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/19/69e42ae892c5a.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '内容涵盖Solitude主题魔改、日常随笔与摄影作品，也分享“尊重分歧”“珍惜眼前”的人生感悟。无明确近期特殊近况，聚焦个人生活记录、博客折腾与影像表达，风格细腻贴合生活。',
			},
			{
				author: 'Eilo',
				sitenick: '',
				title: 'Eilo',
				desc: '等等我记一下',
				link: 'https://aptu.net/',
				linkpage: 'https://aptu.net/friends/',
				feed: 'https://aptu.net/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d4cfa3a8d.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d4cfa3a8d.png',
				archs: ['HTML', 'Netlify'],
				date: '2024-12-09',
				comment: '技术实践与生活随笔，涵盖服务器运维、软件实用技巧等干货，也记录日常感悟与兴趣点滴，兼具技术落地性与生活真实感，风格简洁且内容多元。',
			},
			{
				author: '新锐博客',
				sitenick: '',
				title: '新锐博客',
				desc: '记录学习与分享资源',
				link: 'https://blog.xrbk.cn',
				linkpage: 'https://blog.xrbk.cn/links/',
				feed: 'https://blog.xrbk.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3911e378300.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3911e378300.png',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '涵盖技术实践、生活随笔与兴趣分享，含建站相关技巧、日常感悟等，兼具实用干货与真实生活气息，风格简约质朴，内容多元贴合个人表达。',
			},
			{
				author: '策柯',
				sitenick: '',
				title: '策柯',
				desc: '时矫首而遐观',
				link: 'https://blog.xomoe.cn/',
				linkpage: 'https://blog.xomoe.cn/friends/',
				feed: 'https://blog.xomoe.cn/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e370622676e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e370622676e.webp',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: '聚焦音乐与技术领域。收录华语、日语、二次元等多元曲风歌曲，也分享Linux配置、博客主题优化等技术干货，内容丰富且实用。',
			},
			{
				author: '别碰我的镜头盖',
				sitenick: '',
				title: '别碰我的镜头盖',
				desc: 'AI悦创·创造不同！',
				link: 'https://blog.bornforthis.cn/',
				linkpage: 'https://blog.bornforthis.cn/link/',
				feed: 'https://blog.bornforthis.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e36ec2349b7.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e36ec2349b7.webp',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '融合代码教学与生活记录。近期专注于Python/C++/算法一对一辅导，分享DeepSeek模型实操、信息奥赛题解及摄影课程，并推出高考志愿填报指南。技术专栏涵盖Hexo魔改、自动化脚本开发（如自动生成文章元数据），生活板块记录育儿日常（百天拍照计划、母婴用品清单）与家庭故事。风格幽默接地气，通过代码案例与实战经验降低学习门槛，同时开辟接单渠道，提供作业代写服务，展现极客与奶爸的双重身份。',
			},
			{
				author: '小米里的大麦',
				sitenick: '',
				title: '小米里的大麦',
				desc: '芝兰生于深谷，不以无人而不芳。',
				link: 'https://www.minbit.top/',
				linkpage: 'https://www.minbit.top/link/',
				feed: 'https://www.minbit.top/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d5e36740e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d5e36740e.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '未备案但提供多加速域名。聚焦技术领域，分享C++ STL、Linux、MySQL、算法等干货，也有ChatGPT Go套餐等实用资源，是记录学习与技术分享的平台。',
			},
			{
				author: 'lololowe',
				sitenick: '',
				title: 'lololowe',
				desc: '计网，网安知识分享',
				link: 'https://blog.lololowe.com/',
				linkpage: 'https://blog.lololowe.com/link/',
				feed: 'https://blog.lololowe.com/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a39129949119.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a39129949119.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '深耕网络安全与网络工程领域。近期聚焦OpenStack快速部署实战、Chrome浏览器性能优化、网络协议解析（MTU/链路检测/BFD）等硬核技术，同时分享环境配置心得与存储技术方案。技术专栏涵盖Python自动化脚本、Docker容器化部署、Linux系统调优等实战内容，风格朴实注重实操，通过代码片段与原理图解降低复杂协议理解门槛，是网络工程师与运维人员的实用工具库。',
			},
			{
				author: '静观小窗',
				sitenick: '',
				title: '静观小窗',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.vindo.cn/',
				linkpage: 'https://www.vindo.cn/links',
				feed: 'https://www.vindo.cn/feed.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3912bf5372a.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3912bf5372a.png',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: '技术与人文交织的多元领域，展现开发者与历史爱好者的跨界视角。近期文章涵盖《构建网络友邻对抗信息茧房》的Web生态思考、《BlogsClub中文博客联盟》的社区实践观察，以及《文化隐喻如何塑造认知》的深度书评，并分享了《一键自动化图片压缩工具》等技术干货。作为细节控与复古情怀持有者（痴迷南宋美学与Archer设计哲学），持续探索平面设计创新与独立博客的共生可能，致力于在AI浪潮中守护内容温度。',
			},
			{
				author: 'bbb-lsy07',
				sitenick: '',
				title: 'bbb-lsy07',
				desc: '科技激荡人文，洞见智慧本真',
				link: 'https://blog.tsoo.net/',
				linkpage: 'https://blog.tsoo.net/links',
				feed: 'https://blog.tsoo.net/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e36a9834e9f.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e36a9834e9f.webp',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '聚焦实用技术。分享服务器搭建、博客部署、邮箱/网盘搭建等教程，含服务器测评、AI相关内容，也有研学记录等生活分享，干货满满且易上手。',
			},
			{
				author: '凌尘',
				sitenick: '',
				title: '凌尘',
				desc: '于高山之巅，方见大河奔涌；于群峰之上，更觉长风浩荡。',
				link: 'https://b.icxk.cn/',
				linkpage: 'https://b.icxk.cn/link/',
				feed: '',
				icon: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d399cad9d.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d399cad9d.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '聚焦技术开发与日常分享。技术上涵盖CSS特效、Hexo魔改、服务器搭建（Minecraft、静态网站）、图床搭建等实用教程，也记录软著申请、饮酒计算器等生活点滴，干货与日常兼具。',
			},
			{
				author: 'snows_l',
				sitenick: '',
				title: 'snows_l',
				desc: '小得盈满！',
				link: 'http://snows-l.site/',
				linkpage: 'https://snows-l.site/about/friends',
				feed: '',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3913994ad35.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3913994ad35.png',
				archs: ['PHP', '服务器'],
				date: '2024-12-09',
				comment: '分享前端开发、MacOS 工具、小游戏开发等技术干货，兼载生活随笔。',
			},
			{
				author: 'JustPureH20',
				sitenick: '',
				title: 'JustPureH2O',
				desc: '穷方圆平直之情，尽规矩准绳之用',
				link: 'https://justpureh2o.cn/',
				linkpage: 'https://justpureh2o.cn/friends/',
				feed: 'https://justpureh2o.cn/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e369427ed91.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e369427ed91.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '由高三学子运营，2024-2025 年持续更新。聚焦高中备考与学习干货，涵盖数物化生语文核心知识点、解题策略，也有编程题解、网图溯源等内容，还记录博客新功能构想，实用且贴合学生需求。',
			},
			{
				author: '酥米的小站',
				sitenick: '',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				linkpage: 'https://www.sumi233.top/link/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3694280d70.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3694280d70.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '2025 年末持续更新，站长刚成年、备战高职考。内容以生活碎碎念为主，记录旅游、打工、游戏日常，也分享 Windows 更新日志、星露谷无显卡服务器搭建等实用教程，温馨又有干货。',
			},
			{
				author: 'Tavre',
				sitenick: '',
				title: 'Tavre',
				desc: '茫茫大海 我与你相遇',
				link: 'https://blog.tavr.top/',
				linkpage: 'https://blog.tavr.top/friends/',
				feed: 'https://blog.tavr.top/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a39159385622.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a39159385622.png',
				archs: ['Astro', 'Vercel'],
				date: '2024-12-09',
				comment: '涵盖实用技术教程（宝塔专业版申请、免费图床搭建、AI 绘画、刷课脚本），也分享澎湃 OS 使用体验、CSGO 游戏日常，干货与生活记录兼具，性价比高。',
			},
			{
				author: 'BiuXin',
				sitenick: '与光',
				title: 'BiuXin',
				desc: '一个记录生活、分享心情与日常点滴的博客',
				link: 'https://blog.biuxin.com/',
				linkpage: 'https://blog.biuxin.com/link',
				feed: 'https://blog.biuxin.com/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d887aa229.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/05/02/69f5d887aa229.webp',
				archs: ['Golang', '服务器'],
				date: '2024-12-09',
				comment: '分享服务器运维、项目部署、Hexo 搭建等技术，兼更生活美食、节日随笔。',
			},
			{
				author: '拥抱日出的小屋',
				sitenick: '',
				title: '拥抱日出的小屋',
				desc: '拥抱日出，也拥抱生活',
				link: 'https://ybrc.byside.top/',
				linkpage: 'https://ybrc.byside.top/links',
				feed: 'https://ybrc.byside.top/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3915e93c6a0.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3915e93c6a0.webp',
				archs: ['Halo', '服务器'],
				date: '2025-12-09',
				comment: '记录站长学业转折与高中适应，年末作年度总结、期许2026。内容多元，含Nezha监控、宝塔主题更换等技术教程，服务器状态展示，还有随笔、小说创作，兼具实用干货与生活感悟。',
			},
			{
				author: 'THW',
				sitenick: '',
				title: 'THW',
				desc: '前途似海，来日方长',
				link: 'https://blog.tianhw.top/',
				linkpage: 'https://blog.tianhw.top/friends/',
				feed: 'https://blog.tianhw.top/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a39163676ed0.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a39163676ed0.webp',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-01-18',
				comment: '聚焦Web开发与云原生领域，近期围绕EdgeOne Pages、Astro静态生成等工具展开深度实践，分享自动化图床构建、一键部署方案、纯前端IP获取等硬核教程。',
			},
			{
				author: 'Elykia',
				sitenick: '',
				title: 'Elykia',
				desc: '致以无瑕之人',
				link: 'https://blog.elykia.cn/',
				linkpage: 'https://blog.elykia.cn/link',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3916a7e8b08.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3916a7e8b08.webp',
				archs: ['Golang', 'EdgeOne'],
				date: '2026-01-23',
				comment: '个人文艺哲思博客，站长近期沉浸于诗意表达与生命哲思创作，文章多探讨存在意义、人性本质与艺术疗愈，领域横跨文学、心理学与存在主义哲学，文风空灵隽永，以隐喻与诗性语言构建精神栖居地，在数字时代守护思想纯净性。',
			},
			{
				author: 'Revelation',
				sitenick: '',
				title: 'Revelation',
				desc: '我在等待，等你回来',
				link: 'https://www.040426.xyz/',
				linkpage: 'https://www.040426.xyz/link',
				feed: 'https://www.040426.xyz/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e36559b3d1e.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e36559b3d1e.webp',
				archs: ['Golang', '服务器'],
				date: '2026-01-25',
				comment: '聚焦于个体在虚妄与真实间的挣扎，通过《若为假希望宁无希望》等文探讨现代人精神困境。内容涵盖存在主义反思、自我解构与重建，领域涉及哲学思辨、心灵成长与文学性社会观察，文风冷峻犀利直指当代生存悖论。',
			},
			{
				author: 'LanM',
				sitenick: '',
				title: 'LanM',
				desc: '蓝莓',
				link: 'https://bluelanm.github.io/my-website/',
				linkpage: 'https://bluelanm.github.io/my-website/friend',
				feed: 'https://bluelanm.github.io/my-website/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e365599ddaa.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e365599ddaa.webp',
				archs: ['HTML', 'GitHub Pages'],
				date: '2026-02-05',
				comment: '近期调Docusaurus配置解加载问题，记建站实践，涉技术建站、个人实践，文风务实。',
			},
			{
				author: 'Karina',
				sitenick: '小窝',
				title: '琳琳的小窝',
				desc: '琳琳的小窝',
				link: 'https://karina.xin/',
				linkpage: 'https://karina.xin/friend',
				feed: 'https://blog.karina.xin/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e363ffb139d.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e363ffb139d.webp',
				archs: ['HTML', 'Cloudflare'],
				date: '2026-02-08',
				comment: '近况含Github项目、QQ群。内容有日记、思考、科技数码札、杂谈，涉哲学玄学、记梦绘画，文风带喵系可爱。',
			},
			{
				author: '树萌',
				sitenick: '技术与生活的随笔日记',
				title: '树萌',
				desc: '个人小站，兴趣使然。',
				link: 'https://www.treemoe.cn/',
				linkpage: 'https://www.treemoe.cn/friends.html',
				feed: 'https://www.treemoe.cn/feed/',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a3917255d05f.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a3917255d05f.png',
				archs: ['Typecho', 'EdgeOne'],
				date: '2026-02-23',
				comment: '聚焦Cloudflare创新应用（如R2存储/网络监控）、汉化全流程解析、Typecho/PyCharm深度配置等硬核干货，持续输出开发者实用攻略，兼顾生活杂谈与二次元文化，展现极客浪漫。',
			},
			{
				author: '材料与逻辑',
				sitenick: '',
				title: '材料与逻辑',
				desc: '从原子到结构，从数据到洞察',
				link: 'https://zhyong.site/',
				linkpage: 'https://zhyong.site/links/',
				feed: 'https://zhyong.site/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e363f32e38a.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e363f32e38a.png',
				archs: ['HTML', 'GitHub Pages'],
				date: '2026-02-23',
				comment: '近期高频更新技术干货，涵盖高分子材料研发、Python/AI自动化、铝合金表面处理等技术，延伸至逻辑思维解析。覆盖材料科学、金属工程等领域，文风硬核技术流，注重实践与理论结合。',
			},
			{
				author: 'EXYONE',
				sitenick: '自习室',
				title: 'EXYONE',
				desc: '不会前端的.NET程序员不是好程序员',
				link: 'https://www.exyone.me/',
				linkpage: 'https://exyon.ee/links/',
				feed: 'https://www.exyone.me/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e3604596c18.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e3604596c18.png',
				archs: ['Halo', 'Cloudflare'],
				date: '2026-03-22',
				comment: '专注全栈 / 桌面开发与自托管，2026 年 5 月更新主页，分享技术踩坑、字体 CDN 等项目，兼爱摄影与复古钢笔。',
			},
			{
				author: '栖童',
				sitenick: '小站',
				title: '栖童の小站',
				desc: '越努力,越幸运',
				link: 'https://blog.linux-qitong.top/',
				linkpage: 'https://blog.linux-qitong.top/link',
				feed: 'https://blog.linux-qitong.top/atom.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/05/10/69ffe8766fa3f.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/05/10/69ffe8766fa3f.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-05-10',
				comment: '聚焦 Linux 运维、Hexo 建站、系统问题修复，更新 Butterfly 主题优化，兼更心情随笔，分享实操教程与日常感悟。',
			},
			{
				author: '二叉树树',
				sitenick: '',
				title: 'AcoFork',
				desc: 'Protect What You Love.',
				link: 'https://2x.nz/',
				linkpage: 'https://2x.nz/friends/',
				feed: 'https://2x.nz/rss.xml',
				icon: 'https://s3.qixz.cn/ywty/2026/06/22/6a391830ca2e0.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/06/22/6a391830ca2e0.png',
				archs: ['Astro', 'Cloudflare'],
				date: '2025-12-09',
				comment: '大专在读折腾党，从 Win 到 Mac 再到自组台式，深耕 Serverless、NAS、随机图 API 与自建服务，兼顾二次元工具与博客实操。',
			},
		],
	},
	{
		name: '网络组织',
		desc: '一个人的寂寞，一群人的狂欢',
		entries: [
			{
				author: '开往',
				sitenick: '友链接力!',
				title: '开往',
				desc: '让传统友链“活跃”，让网页相互接力，让流量相互流动，让网络开放起来',
				link: 'https://www.travellings.cn/',
				linkpage: 'https://list.travellings.cn/',
				feed: '',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e35fe7e2faf.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e35fe7e2faf.png',
				archs: ['VitePress', 'Cloudflare'],
				date: '2025-07-27',
			},
			{
				author: '揪蝉',
				sitenick: '',
				title: '揪蝉',
				desc: '每一次点击都是一次穿越发现',
				link: 'https://hi.jiuchan.org/',
				linkpage: 'https://hi.jiuchan.org/discover',
				feed: '',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e35acf2a2ce.webp',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e35acf2a2ce.webp',
				archs: ['Next.js', 'Cloudflare'],
				date: '2025-06-22',
			},
			{
				author: 'BlogsClub',
				sitenick: '',
				title: 'BlogsClub',
				desc: '个人博客俱乐部',
				link: 'https://www.blogsclub.org/',
				linkpage: 'https://www.blogsclub.org/members.html',
				feed: 'https://www.blogsclub.org/feed.xml?sort=time',
				icon: 'https://s3.qixz.cn/ywty/2026/04/18/69e35e8d63904.png',
				avatar: 'https://s3.qixz.cn/ywty/2026/04/18/69e35e8d63904.png',
				archs: ['Golang', '服务器'],
				date: '2025-06-22',
			},
		],
	},
	{
		name: '失联友友',
		desc: '离别是为了更好的重逢',
		entries: [
			{
				author: '秘柯絮语',
				sitenick: '',
				title: '秘柯絮语',
				desc: 'My Inner Opinion Collection',
				link: '',
				linkpage: '',
				feed: '',
				icon: '',
				avatar: '',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '无解析',
			},
			{
				author: 'Evilrabbit',
				sitenick: '',
				title: 'Evilrabbit',
				desc: '爱 Coding 爱生活',
				link: '',
				linkpage: '',
				feed: '',
				icon: '',
				avatar: '',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '403 Forbidden',
			},
			{
				author: '梨尽兴',
				sitenick: '',
				title: '梨尽兴',
				desc: 'A place for peace',
				link: '',
				linkpage: '',
				feed: '',
				icon: '',
				avatar: '',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: 'net::ERR_CERT_DATE_INVALID',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
